/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-20 09:42:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.Connection;
import com.db.DbConnect;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1700322569110L));
    _jspx_dependants.put("/all_component/allCss.jsp", Long.valueOf(1700145987220L));
    _jspx_dependants.put("jar:file:/D:/Eclipse_workspace/Ebook/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Ebook-App/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602863172000L));
    _jspx_dependants.put("/all_component/navbar.jsp", Long.valueOf(1700473370004L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.db.DbConnect");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Ebook</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"all_component/styles.css\"></link>");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".back-img {\r\n");
      out.write("	background: url(\"img/back_img.jpg\");\r\n");
      out.write("	height: 50vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".crd-ho:hover {\r\n");
      out.write("	background-color: #fcf7f7;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"main-container\">\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<style>\n");
      out.write("	a:hover {\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\n");
      out.write("</style>\r\n");
      out.write("<div class=\"container=fluid\"\r\n");
      out.write("	style=\"height: 10px; background-color: #303f9f\"></div>\r\n");
      out.write("<div class=\"container-fluid p-3\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-3\">\r\n");
      out.write("			<h3 class=\"text-success\">\r\n");
      out.write("				<a href=\"index.jsp\" class=\"text-success\"><i class=\"fa-solid fa-book\"></i> Ebooks</a>\r\n");
      out.write("			</h3>\r\n");
      out.write("	    <button id=\"lang-en\">English</button>\r\n");
      out.write("	    <button id=\"lang-ru\">Russian</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3\">\r\n");
      out.write("			<a href=\"login.jsp\" class=\"btn btn-success\">Login</a> <a href=\"register.jsp\"\r\n");
      out.write("				class=\"btn btn-primary\">Register</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-custom\">\r\n");
      out.write("	<a class=\"navbar-brand\" href=\"#\"><i class=\"fa-solid fa-house\"></i></a>\r\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("		data-target=\"#navbarSupportedContent\"\r\n");
      out.write("		aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("		aria-label=\"Toggle navigation\">\r\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("	</button>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">Home<span\r\n");
      out.write("					class=\"sr-only\">(current)</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><i\r\n");
      out.write("					class=\"fas fa-book-open\"></i> Recent Book</a></li>\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><i\r\n");
      out.write("					class=\"fas fa-book-open\"></i> New Book</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link disabled\"\r\n");
      out.write("				href=\"#\"><i class=\"fas fa-book-open\"></i> Old Book</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("			<button class=\"btn btn-light my-2 my-sm-0 ml-1\" type=\"submit\">\r\n");
      out.write("				<i class=\"fas fa-cog\"></i>Setting\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"btn btn-light my-2 my-sm-0 ml-1\" type=\"submit\">\r\n");
      out.write("				<i class=\"fas fa-phone-square-alt\"></i> Contact Us\r\n");
      out.write("			</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid back-img\">\r\n");
      out.write("			<h2 class=\"text-center\" id=\"lang-ebook-system\">EBook Managment System</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Recent Book -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h3 class=\"text-center\" id=\"lang-recent-book\">Recent Book</h3>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book1.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name1\">Name 1</p>\r\n");
      out.write("							<p id=\"lang-author1\">Author 1</p>\r\n");
      out.write("							<p id=\"lang-category1\">Categories: New</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book2.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name2\">Name 2</p>\r\n");
      out.write("							<p id=\"lang-author2\">Author 2</p>\r\n");
      out.write("							<p id=\"lang-category2\">Categories: New</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book3.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name3\">Name 3</p>\r\n");
      out.write("							<p id=\"lang-author3\">Author 3</p>\r\n");
      out.write("							<p id=\"lang-category3\">Categories: Old</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book4.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name3\">Name3</p>\r\n");
      out.write("							<p id=\"lang-author3\">Author</p>\r\n");
      out.write("							<p class=\"lang-category3\">Categories: Old</p>\r\n");
      out.write("							<div id=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"text-center mt-2\">\r\n");
      out.write("				<a href=\"\" class=\"btn btn-danger btn-sm text-white\" id=\"lang-view-all\">View All</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Recent Book  -->\r\n");
      out.write("\r\n");
      out.write("		<!--<div style=\"height: 1px; width: 1080px; background-color: #f7f7f7; margin: 20px 20px\"></div> -->\r\n");
      out.write("		<hr>\r\n");
      out.write("\r\n");
      out.write("		<!-- Start New Book -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h3 class=\"text-center\" id=\"lang-new-book\">New Book</h3>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book1.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name1\">Name1</p>\r\n");
      out.write("							<p id=\"lang-author1\">Author</p>\r\n");
      out.write("							<p id=\"lang-category1\">Categories: New</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book2.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name2\">Name2</p>\r\n");
      out.write("							<p id=\"lang-author2\">Author</p>\r\n");
      out.write("							<p id=\"lang-category2\">Categories: New</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book3.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name3\">Name3</p>\r\n");
      out.write("							<p id=\"lang-author3\">Author</p>\r\n");
      out.write("							<p id=\"lang-category3\">Categories: Old</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card crd-ho\">\r\n");
      out.write("						<div class=\"card-body text-center\">\r\n");
      out.write("							<img alt=\"\" src=\"book/book4.jpg\"\r\n");
      out.write("								style=\"width: 150px; height: 200px;\" class=\"img-thumblin\">\r\n");
      out.write("							<p id=\"lang-name3\">Name3</p>\r\n");
      out.write("							<p id=\"lang-author3\">Author</p>\r\n");
      out.write("							<p id=\"lang-category3\">Categories: New</p>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<a href=\"\" class=\"btn btn-danger btn-sm ml-2\" id=\"lang-add-cart\"><i\r\n");
      out.write("									class=\"fas fa-cart-plus\"></i> Add Cart</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-success btn-sm ml-1\" id=\"lang-view-details\">View Details</a> <a href=\"\"\r\n");
      out.write("									class=\"btn btn-danger btn-sm ml-1\">299</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"text-center mt-2\">\r\n");
      out.write("				<a href=\"\" class=\"btn btn-danger btn-sm text-white\" id=\"lang-view-all\">View All</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End New Book  -->\r\n");
      out.write("\r\n");
      out.write("		<hr>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "all_component/footer_main.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "all_component/script.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
